const fs = require('fs');
const path = require('path');

function normalizeStr(text) {
  return text
    .toLowerCase()
    .replace(/[čć]/g, 'c')
    .replace(/đ/g, 'dj')
    .replace(/š/g, 's')
    .replace(/ž/g, 'z')
    .replace(/[^a-z0-9\s]/g, '')
    .trim();
}

function makeSearchTerms(title, artist) {
  const normTitle = normalizeStr(title);
  const normArtist = normalizeStr(artist);
  const terms = new Set();
  terms.add(normTitle);
  terms.add(normArtist);
  terms.add(`${normArtist} ${normTitle}`);
  terms.add(`${normTitle} ${normArtist}`);

  // Add individual words if meaningful
  normTitle.split(/\s+/).forEach(w => { if (w.length > 2) terms.add(w); });
  normArtist.split(/\s+/).forEach(w => { if (w.length > 2) terms.add(w); });

  return Array.from(terms);
}

// 1. Expanded Narodna (iconic folk, kafana, sevdah, novokomponovana)
const NARODNA_ITEMS = [
  { artist: 'Toma Zdravković', title: 'Za Ljiljanu', year: 1984 },
  { artist: 'Toma Zdravković', title: 'Šta će mi život', year: 1970 },
  { artist: 'Toma Zdravković', title: 'Dotako sam dno života', year: 1982 },
  { artist: 'Toma Zdravković', title: 'Prokleta je ova nedelja', year: 1987 },
  { artist: 'Toma Zdravković', title: 'Pesme moje', year: 1988 },
  { artist: 'Toma Zdravković', title: 'Branka', year: 1981 },
  { artist: 'Toma Zdravković', title: 'Tužno leto', year: 1971 },
  { artist: 'Šaban Šaulić', title: 'Dođi da ostarimo zajedno', year: 1978 },
  { artist: 'Šaban Šaulić', title: 'Odlaziš, odlaziš', year: 1986 },
  { artist: 'Šaban Šaulić', title: 'Gordana', year: 1989 },
  { artist: 'Šaban Šaulić', title: 'Kraljica srca moga', year: 1986 },
  { artist: 'Šaban Šaulić', title: 'Sneg je opet Snežana', year: 1981 },
  { artist: 'Šaban Šaulić', title: 'Žal', year: 2013 },
  { artist: 'Šaban Šaulić', title: 'Ilda Šaulić', year: 1975 },
  { artist: 'Šaban Šaulić', title: 'Sanela', year: 1979 },
  { artist: 'Šaban Šaulić', title: 'Dva galeba bela', year: 1979 },
  { artist: 'Miroslav Ilić', title: 'Božanstvena ženo', year: 1983 },
  { artist: 'Miroslav Ilić', title: 'Pozdravi je, pozdravi', year: 1982 },
  { artist: 'Miroslav Ilić', title: 'Nije život jedna žena', year: 1981 },
  { artist: 'Miroslav Ilić', title: 'Tebi', year: 1986 },
  { artist: 'Miroslav Ilić', title: 'Voleo sam devojku iz grada', year: 1972 },
  { artist: 'Miroslav Ilić', title: 'Polomiću čaše od kristala', year: 1979 },
  { artist: 'Miroslav Ilić', title: 'Ova noć', year: 1984 },
  { artist: 'Miroslav Ilić', title: 'Još te nešto čini izuzetnom', year: 1980 },
  { artist: 'Haris Džinović', title: 'Muštuluk', year: 2009 },
  { artist: 'Haris Džinović', title: 'I tebe sam sit kafano', year: 1989 },
  { artist: 'Haris Džinović', title: 'Pariške kapije', year: 2007 },
  { artist: 'Haris Džinović', title: 'Sjećaš li se one noći', year: 1989 },
  { artist: 'Haris Džinović', title: 'Odlazi, nestaje', year: 1991 },
  { artist: 'Haris Džinović', title: 'Dajte vina hoću lom', year: 1991 },
  { artist: 'Haris Džinović', title: 'Poznaćeš me', year: 1989 },
  { artist: 'Halid Bešlić', title: 'Prvi poljubac', year: 2003 },
  { artist: 'Halid Bešlić', title: 'Miljacka', year: 2007 },
  { artist: 'Halid Bešlić', title: 'Romanija', year: 2013 },
  { artist: 'Halid Bešlić', title: 'Ja bez tebe ne mogu da živim', year: 2018 },
  { artist: 'Halid Bešlić', title: 'U meni jesen je', year: 1998 },
  { artist: 'Halid Bešlić', title: 'Zlatne strune', year: 1988 },
  { artist: 'Halid Bešlić', title: 'Eh kad bi ti', year: 1987 },
  { artist: 'Sinan Sakić', title: 'Ej od kad sam se rodio', year: 1987 },
  { artist: 'Sinan Sakić', title: 'Sudbina me na put šalje', year: 1990 },
  { artist: 'Sinan Sakić', title: 'Pevaj mi o njoj', year: 1986 },
  { artist: 'Sinan Sakić', title: 'Reci sve želje', year: 1985 },
  { artist: 'Sinan Sakić', title: 'Da se opet rodim', year: 2000 },
  { artist: 'Sinan Sakić', title: 'Mene kući niko ne čeka', year: 2005 },
  { artist: 'Sinan Sakić', title: 'Zoko moja Zoko', year: 1989 },
  { artist: 'Mile Kitić', title: 'Kraljica trotoara', year: 1996 },
  { artist: 'Mile Kitić', title: 'Kockar', year: 1999 },
  { artist: 'Mile Kitić', title: 'Šampanjac', year: 2005 },
  { artist: 'Mile Kitić', title: 'Plava ciganko', year: 2001 },
  { artist: 'Mile Kitić', title: 'Smejem se a plače mi se', year: 2003 },
  { artist: 'Mile Kitić', title: 'Čaša ljubavi', year: 1984 },
  { artist: 'Mile Kitić', title: 'Policijo oprosti mi', year: 2002 },
  { artist: 'Dragana Mirković', title: 'Pitaju me u mom kraju', year: 1992 },
  { artist: 'Dragana Mirković', title: 'Milo moje što te nema', year: 1993 },
  { artist: 'Dragana Mirković', title: 'Luče moje', year: 2006 },
  { artist: 'Dragana Mirković', title: 'Opojni su zumbuli', year: 1995 },
  { artist: 'Dragana Mirković', title: 'Umirem majko', year: 1991 },
  { artist: 'Dragana Mirković', title: 'Spasi me samoće', year: 1986 },
  { artist: 'Dragana Mirković', title: 'Sama', year: 2000 },
  { artist: 'Lepa Brena', title: 'Luda za tobom', year: 1996 },
  { artist: 'Lepa Brena', title: 'Čačak, Čačak', year: 1982 },
  { artist: 'Lepa Brena', title: 'Mile voli disko', year: 1982 },
  { artist: 'Lepa Brena', title: 'Sitnije, Cile, sitnije', year: 1983 },
  { artist: 'Lepa Brena', title: 'Duge noge', year: 1983 },
  { artist: 'Lepa Brena', title: 'Golube', year: 1989 },
  { artist: 'Lepa Brena', title: 'Poželi sreću drugima', year: 1989 },
  { artist: 'Lepa Brena', title: 'Ti si moj greh', year: 1996 },
  { artist: 'Ceca', title: 'Beograd', year: 1995 },
  { artist: 'Ceca', title: 'Idi dok si mlad', year: 1995 },
  { artist: 'Ceca', title: 'Kukavica', year: 1993 },
  { artist: 'Ceca', title: 'Vazduh koji dišem', year: 1993 },
  { artist: 'Ceca', title: 'Nagovori', year: 1999 },
  { artist: 'Ceca', title: 'Dokaz', year: 1999 },
  { artist: 'Ceca', title: 'Da li to ljubav pravi od nas slabiće', year: 1995 },
  { artist: 'Ceca', title: 'Maskarada', year: 1997 },
  { artist: 'Ceca', title: 'Lepotan', year: 1989 },
  { artist: 'Ceca', title: 'Zabranjeni grad', year: 2001 },
  { artist: 'Ceca', title: 'Tačno je', year: 2001 },
  { artist: 'Ceca', title: 'Gore od ljubavi', year: 2004 },
  { artist: 'Ceca', title: 'Pustite me da ga vidim', year: 1990 },
  { artist: 'Aca Lukas', title: 'Pesma od bola', year: 1997 },
  { artist: 'Aca Lukas', title: 'Kafana na Balkanu', year: 1998 },
  { artist: 'Aca Lukas', title: 'Lična karta', year: 1998 },
  { artist: 'Aca Lukas', title: 'Nisam preživeo', year: 2003 },
  { artist: 'Aca Lukas', title: 'Nešto protiv bolova', year: 2001 },
  { artist: 'Aca Lukas', title: 'Dijabolik', year: 2003 },
  { artist: 'Aca Lukas', title: 'Bele ruže', year: 1996 },
  { artist: 'Aca Lukas', title: 'By Pass', year: 2008 },
  { artist: 'Aca Lukas', title: 'Lešće', year: 2008 },
  { artist: 'Džej Ramadanovski', title: 'Nedelja', year: 1991 },
  { artist: 'Džej Ramadanovski', title: 'Gde ću sad moja ružo', year: 1992 },
  { artist: 'Džej Ramadanovski', title: 'Uspeo sam u životu', year: 1991 },
  { artist: 'Džej Ramadanovski', title: 'Ugasila si me', year: 1991 },
  { artist: 'Džej Ramadanovski', title: 'Sunce ljubavi', year: 1995 },
  { artist: 'Džej Ramadanovski', title: 'Zato', year: 1993 },
  { artist: 'Džej Ramadanovski', title: 'Imati pa nemati', year: 2001 },
  { artist: 'Džej Ramadanovski', title: 'Od ljubavi do mržnje', year: 1995 },
  { artist: 'Predrag Živković Tozovac', title: 'Ti si me čekala', year: 1978 },
  { artist: 'Predrag Živković Tozovac', title: 'Oči jedne žene', year: 1972 },
  { artist: 'Predrag Živković Tozovac', title: 'Vlajna', year: 1971 },
  { artist: 'Predrag Živković Tozovac', title: 'Prazna čaša na mom stolu', year: 1984 },
  { artist: 'Predrag Živković Tozovac', title: 'Mirjana', year: 1971 },
  { artist: 'Predrag Živković Tozovac', title: 'Ide Mile lajkovačkom prugom', year: 1974 },
  { artist: 'Predrag Gojković Cune', title: 'Janičar', year: 1981 },
  { artist: 'Predrag Gojković Cune', title: 'Kafu mi draga ispeci', year: 1962 },
  { artist: 'Predrag Gojković Cune', title: 'Ljubav mi srce mori', year: 1973 },
  { artist: 'Zorica Brunclik', title: 'A tebe nema', year: 1982 },
  { artist: 'Zorica Brunclik', title: 'Otkopčaj prsluk', year: 1984 },
  { artist: 'Zorica Brunclik', title: 'Kada bi me pitali', year: 1986 },
  { artist: 'Zorica Brunclik', title: 'Ne daj da nas rastave', year: 1975 },
  { artist: 'Zorica Brunclik', title: 'Avlije, avlije', year: 1990 },
  { artist: 'Vesna Zmijanac', title: 'Nevera moja', year: 1985 },
  { artist: 'Vesna Zmijanac', title: 'Kazni me, kazni', year: 1988 },
  { artist: 'Vesna Zmijanac', title: 'Kunem ti se životom', year: 1987 },
  { artist: 'Vesna Zmijanac', title: 'Malo po malo', year: 1995 },
  { artist: 'Vesna Zmijanac', title: 'Idem preko zemlje Srbije', year: 1994 },
  { artist: 'Ana Bekuta', title: 'Zlatiborske zore', year: 1996 },
  { artist: 'Ana Bekuta', title: 'Ja nisam rođena da živim sama', year: 1985 },
  { artist: 'Ana Bekuta', title: 'Kralj ponoći', year: 1999 },
  { artist: 'Ana Bekuta', title: 'Bekrija', year: 1991 },
  { artist: 'Ana Bekuta', title: 'Veseljak', year: 1993 },
  { artist: 'Snežana Đurišić', title: 'Kućica u cveću', year: 1983 },
  { artist: 'Snežana Đurišić', title: 'Pričaj mi, pričaj', year: 1985 },
  { artist: 'Snežana Đurišić', title: 'Kleo se, kleo', year: 1997 },
  { artist: 'Snežana Đurišić', title: 'Niko me nije voleo kao ti', year: 1992 },
  { artist: 'Nada Topčagić', title: 'Jutro je', year: 1989 },
  { artist: 'Nada Topčagić', title: 'Treba mi rame tvoje', year: 1982 },
  { artist: 'Nada Topčagić', title: 'Izvini, dušo, izvini', year: 1984 },
  { artist: 'Marinko Rokvić', title: 'Skitnica', year: 2003 },
  { artist: 'Marinko Rokvić', title: 'Da volim drugu ne mogu', year: 1982 },
  { artist: 'Marinko Rokvić', title: 'Zanela me svetla velikoga grada', year: 1984 },
  { artist: 'Marinko Rokvić', title: 'Ovo je moja kuća', year: 2003 },
  { artist: 'Jašar Ahmedovski', title: 'Jednoj ženi za sećanje', year: 1982 },
  { artist: 'Jašar Ahmedovski', title: 'Isplači se, biće ti lakše', year: 1983 },
  { artist: 'Jašar Ahmedovski', title: 'Svako svome mora da se vraća', year: 1984 },
  { artist: 'Jašar Ahmedovski', title: 'Ceo grad je plakao za nama', year: 1986 },
  { artist: 'Ipče Ahmedovski', title: 'Da ti gužvam postelju', year: 1993 },
  { artist: 'Ipče Ahmedovski', title: 'Oči crne, oči lažne', year: 1991 },
  { artist: 'Ipče Ahmedovski', title: 'Plačite oči moje', year: 1990 },
  { artist: 'Ljuba Aličić', title: 'Ti ne ličiš ni na jednu', year: 1986 },
  { artist: 'Ljuba Aličić', title: 'Ciganin sam, al najlepši', year: 2003 },
  { artist: 'Ljuba Aličić', title: 'Plačite sa mnom jesenje kiše', year: 1988 },
  { artist: 'Ljuba Aličić', title: 'Samo ona može u život da me vrati', year: 1985 },
  { artist: 'Šerif Konjević', title: 'Pusti me već jednom', year: 1997 },
  { artist: 'Šerif Konjević', title: 'Kasno će biti kasnije', year: 2002 },
  { artist: 'Šerif Konjević', title: 'Zalutala sudbina', year: 1988 },
  { artist: 'Šerif Konjević', title: 'Pitaju me pitaju', year: 1985 },
  { artist: 'Enes Begović', title: 'Sve imao samo tebe ne', year: 2002 },
  { artist: 'Enes Begović', title: 'Bosanac', year: 1987 },
  { artist: 'Enes Begović', title: 'Kaja', year: 2004 },
  { artist: 'Mitar Mirić', title: 'Ne može nam niko ništa', year: 1989 },
  { artist: 'Mitar Mirić', title: 'Voli me danas više nego juče', year: 1980 },
  { artist: 'Mitar Mirić', title: 'Doviđenja, društvo staro', year: 1981 },
  { artist: 'Mitar Mirić', title: 'Ciganče', year: 2004 },
  { artist: 'Šemsa Suljaković', title: 'Pristajem na sve', year: 1986 },
  { artist: 'Šemsa Suljaković', title: 'Zar za mene nema sreće', year: 1987 },
  { artist: 'Šemsa Suljaković', title: 'Javi se oteraj tugu', year: 1988 },
  { artist: 'Šemsa Suljaković', title: 'Mi se volimo', year: 1986 },
  { artist: 'Kemal Malovčić', title: 'Ko gubi', year: 1986 },
  { artist: 'Kemal Malovčić', title: 'Rekla si mi da ne voliš zimu', year: 1985 },
  { artist: 'Kemal Malovčić', title: 'Oženjen sam', year: 1987 },
  { artist: 'Kemal Malovčić', title: 'Tek, tek', year: 2002 },
  { artist: 'Nedeljko Bajić Baja', title: 'Zapisano je u vremenu', year: 2007 },
  { artist: 'Nedeljko Bajić Baja', title: 'Ginisov rekord', year: 2002 },
  { artist: 'Nedeljko Bajić Baja', title: 'Mini suknja', year: 2004 },
  { artist: 'Nedeljko Bajić Baja', title: 'Tipičan muškarac', year: 2007 },
  { artist: 'Seka Aleksić', title: 'Crno i zlatno', year: 2003 },
  { artist: 'Seka Aleksić', title: 'Aspirin', year: 2007 },
  { artist: 'Seka Aleksić', title: 'Koma', year: 2017 },
  { artist: 'Seka Aleksić', title: 'Poslednji let', year: 2007 },
  { artist: 'Seka Aleksić', title: 'Da sam muško', year: 2003 },
  { artist: 'Stoja', title: 'Bela ciganka', year: 2013 },
  { artist: 'Stoja', title: 'Samo', year: 2000 },
  { artist: 'Stoja', title: 'Potopiću ovaj splav', year: 2008 },
  { artist: 'Stoja', title: 'Ćiki, ćiki', year: 1999 },
  { artist: 'Dara Bubamara', title: 'Košava sa Dunava', year: 1993 },
  { artist: 'Dara Bubamara', title: 'Zidovi', year: 2007 },
  { artist: 'Dara Bubamara', title: 'Dodirni me', year: 2005 },
  { artist: 'Dara Bubamara', title: 'Vero, nevero', year: 2003 },
  { artist: 'Jana', title: 'Šta će ti pevačica', year: 2002 },
  { artist: 'Jana', title: 'Barabar', year: 2001 },
  { artist: 'Jana', title: 'Kući, kući', year: 2003 },
  { artist: 'Viki Miljković', title: 'Koka kola, marlboro, suzuki', year: 1994 },
  { artist: 'Viki Miljković', title: 'Mahinalno', year: 2005 },
  { artist: 'Viki Miljković', title: 'Crno na belo', year: 2003 },
  { artist: 'Sanja Đorđević', title: 'Sanja', year: 2003 },
  { artist: 'Sanja Đorđević', title: 'Za inat rođena', year: 2004 },
  { artist: 'Boban Rajović', title: 'Usne boje vina', year: 2007 },
  { artist: 'Boban Rajović', title: 'Provokacija', year: 2006 },
  { artist: 'Šako Polumenta', title: 'Dišem za tebe', year: 2004 },
  { artist: 'Šako Polumenta', title: 'Punomoć', year: 2006 },
  { artist: 'Dado Polumenta', title: 'Kafana', year: 2007 },
  { artist: 'Dado Polumenta', title: 'Anamarija', year: 2005 },
  { artist: 'Halid Muslimović', title: 'Mene je učilo vrijeme', year: 1984 },
  { artist: 'Halid Muslimović', title: 'Oj, jarane, jarane', year: 1985 },
  { artist: 'Halid Muslimović', title: 'Znam za sve sam kriv', year: 1983 },
  { artist: 'Zorica Marković', title: 'Lijte kiše', year: 1991 },
  { artist: 'Bora Drljača', title: 'Stari vuk', year: 2004 },
  { artist: 'Bora Drljača', title: 'Plači mala, plači', year: 1998 },
  { artist: 'Baja Mali Knindža', title: 'Ptico moja, bijeli labude', year: 1999 },
  { artist: 'Baja Mali Knindža', title: 'Morem plovi jedna mala barka', year: 1995 },
  { artist: 'Nino Rešić', title: 'Što mi noći nemaju svanuća', year: 1995 },
  { artist: 'Nino Rešić', title: 'Usne vrele kao žar', year: 1993 },
  { artist: 'Nino Rešić', title: 'Donesi divlje mirise', year: 1994 },
  { artist: 'Darko Lazić', title: 'Majko', year: 2019 },
  { artist: 'Darko Lazić', title: 'Anegdota', year: 2021 },
  { artist: 'Darko Lazić', title: 'Korak do sna', year: 2010 },
  { artist: 'Aleksandra Mladenović', title: 'Ljubav ili ludilo', year: 2017 },
  { artist: 'Aleksandra Mladenović', title: 'Poseban', year: 2019 },
  { artist: 'Tanja Savić', title: 'Zlatnik', year: 2008 },
  { artist: 'Tanja Savić', title: 'Tako mlada', year: 2005 },
  { artist: 'Tanja Savić', title: 'Gora gora', year: 2009 },
  { artist: 'Slavica Ćukteraš', title: 'Zvaćeš je mojim imenom', year: 2005 },
  { artist: 'Slavica Ćukteraš', title: 'Prevari me', year: 2006 },
  { artist: 'Bane Mojićević', title: 'Ostavi me, neće boleti', year: 2005 },
  { artist: 'Milan Stanković', title: 'Ovo je Balkan', year: 2010 },
  { artist: 'Milan Stanković', title: 'Solo', year: 2009 },
  { artist: 'Saša Matić', title: 'Maskara', year: 2001 },
  { artist: 'Saša Matić', title: 'Kad ljubav zakasni', year: 2002 },
  { artist: 'Saša Matić', title: 'Ko te ljubi ovih dana', year: 2005 },
  { artist: 'Saša Matić', title: 'Kralj izgubljenih stvari', year: 2005 },
  { artist: 'Saša Matić', title: 'Ruzmarin', year: 2005 },
  { artist: 'Saša Matić', title: 'Nađi novu ljubav', year: 2011 },
  { artist: 'Saša Matić', title: 'Prejako', year: 2017 },
  { artist: 'Dejan Matić', title: 'Niko i neko', year: 2004 },
  { artist: 'Dejan Matić', title: 'Burma', year: 2004 },
  { artist: 'Dejan Matić', title: 'Ona je moja', year: 2013 },
  { artist: 'Dejan Matić', title: 'Dozvola za ljubav', year: 2010 },
  { artist: 'Jovan Perišić', title: 'Moje najmilije', year: 2007 },
  { artist: 'Jovan Perišić', title: 'Znaš me, znam te', year: 2009 },
  { artist: 'Jovan Perišić', title: 'Sunce se rađa', year: 2011 },
  { artist: 'Jovan Perišić', title: 'Rekom bola', year: 2013 },
  { artist: 'Indira Radić', title: 'Zmaj', year: 2003 },
  { artist: 'Indira Radić', title: 'Lopov', year: 2002 },
  { artist: 'Indira Radić', title: 'Bio si mi drag', year: 2003 },
  { artist: 'Indira Radić', title: 'Tetovaža', year: 2003 },
  { artist: 'Indira Radić', title: 'Nisam sumnjala', year: 2003 },
  { artist: 'Indira Radić', title: 'April', year: 2005 },
  { artist: 'Lepa Lukić', title: 'Od izvora dva putića', year: 1964 },
  { artist: 'Lepa Lukić', title: 'Srce je moje violina', year: 1989 },
  { artist: 'Lepa Lukić', title: 'Čaj za dvoje', year: 1973 },
  { artist: 'Silvana Armenulić', title: 'Noćas mi srce pati', year: 1971 },
  { artist: 'Silvana Armenulić', title: 'Rane moje', year: 1972 },
  { artist: 'Silvana Armenulić', title: 'Ciganine, sviraj, sviraj', year: 1972 },
  { artist: 'Safet Isović', title: 'Moj dilbere', year: 1972 },
  { artist: 'Safet Isović', title: 'Kad ja pođoh na Bembašu', year: 1967 },
  { artist: 'Safet Isović', title: 'Šehidski rastanak', year: 1993 },
  { artist: 'Beki Bekić', title: 'Marama šarena', year: 1992 },
  { artist: 'Beki Bekić', title: 'Ti si me opila', year: 1991 },
  { artist: 'Šeki Turković', title: 'Poslednji boem', year: 1988 },
  { artist: 'Šeki Turković', title: 'Dotaknuću', year: 1989 },
  { artist: 'Rođa Raičević', title: 'Rastanak', year: 1993 },
  { artist: 'Rođa Raičević', title: 'U tebe sam zaljubljen', year: 1995 },
  { artist: 'Rođa Raičević', title: 'Draga', year: 1997 },
  { artist: 'Medeni Mesec', title: 'Ivana', year: 1998 },
  { artist: 'Medeni Mesec', title: 'Bosim nogama bih vatru gazio', year: 2000 },
  { artist: 'Željko Šašić', title: 'Gori more', year: 1994 },
  { artist: 'Željko Šašić', title: 'Kao na dlanu', year: 1995 },
  { artist: 'Željko Šašić', title: 'Metak', year: 1996 },
  { artist: 'Biljana Jevtić', title: 'Evo ti srce na dlanu', year: 1986 },
  { artist: 'Biljana Jevtić', title: 'Proklet da je ovaj život', year: 1987 },
  { artist: 'Mina Kostić', title: 'Slavija', year: 2001 },
  { artist: 'Mina Kostić', title: 'Stariji čovek', year: 2004 },
  { artist: 'Suzana Jovanović', title: 'Džabe care', year: 1997 },
  { artist: 'Suzana Jovanović', title: 'Plavuša', year: 1998 },
  { artist: 'Goca Božinovska', title: 'Okovana zlatom', year: 1998 },
  { artist: 'Zlata Petrović', title: 'Dođi da mi ruke greješ', year: 1989 },
  { artist: 'Sanja Maletić', title: 'Mlađi', year: 2001 },
  { artist: 'Osman Hadžić', title: 'Ti mene ne voliš', year: 2005 },
  { artist: 'Osman Hadžić', title: 'Prezime', year: 2002 }
];

// 2. Expanded Ex-Yu Rock & Pop Evergreen
const EXYU_ITEMS = [
  { artist: 'Bijelo Dugme', title: 'Sanjao sam noćas da te nemam', year: 1976 },
  { artist: 'Bijelo Dugme', title: 'Ne spavaj mala moja muzika dok svira', year: 1974 },
  { artist: 'Bijelo Dugme', title: 'Ružica si bila', year: 1986 },
  { artist: 'Bijelo Dugme', title: 'Padaju zvijezde', year: 1984 },
  { artist: 'Bijelo Dugme', title: 'Tako ti je mala moja kad ljubi Bosanac', year: 1975 },
  { artist: 'Bijelo Dugme', title: 'Đurđevdan je a ja nisam s onom koju volim', year: 1988 },
  { artist: 'Bijelo Dugme', title: 'Doživjeti stotu', year: 1980 },
  { artist: 'Bijelo Dugme', title: 'Evo zakleću se', year: 1988 },
  { artist: 'Bijelo Dugme', title: 'Ako ima Boga', year: 1988 },
  { artist: 'Bijelo Dugme', title: 'Hop cup', year: 1975 },
  { artist: 'Zdravko Čolić', title: 'Pusti, pusti modu', year: 1980 },
  { artist: 'Zdravko Čolić', title: 'Glavo luda', year: 1977 },
  { artist: 'Zdravko Čolić', title: 'Ti si mi u krvi', year: 1984 },
  { artist: 'Zdravko Čolić', title: 'Kao moja mati', year: 2006 },
  { artist: 'Zdravko Čolić', title: 'Stanica Podlugovi', year: 1983 },
  { artist: 'Zdravko Čolić', title: 'Zvao sam je Emili', year: 1975 },
  { artist: 'Zdravko Čolić', title: 'Jedna zima sa Kristinom', year: 1977 },
  { artist: 'Zdravko Čolić', title: 'Ruška', year: 1984 },
  { artist: 'Zdravko Čolić', title: 'Pjevam danju, pjevam noću', year: 1977 },
  { artist: 'Zdravko Čolić', title: 'Zagrli me', year: 1977 },
  { artist: 'Riblja Čorba', title: 'Lutka sa naslovne strane', year: 1978 },
  { artist: 'Riblja Čorba', title: 'Ostani đubre do kraja', year: 1979 },
  { artist: 'Riblja Čorba', title: 'Pogledaj dom svoj, anđele', year: 1985 },
  { artist: 'Riblja Čorba', title: 'Kad sam bio mlad', year: 1992 },
  { artist: 'Riblja Čorba', title: 'Nemoj da ideš mojom ulicom', year: 1982 },
  { artist: 'Riblja Čorba', title: 'Kada padne noć', year: 1987 },
  { artist: 'Riblja Čorba', title: 'Amsterdam', year: 1986 },
  { artist: 'Riblja Čorba', title: 'Gde si u ovom glupom hotelu', year: 1987 },
  { artist: 'Riblja Čorba', title: 'Dva dinara, druže', year: 1981 },
  { artist: 'Bajaga i Instruktori', title: 'Tišina', year: 1988 },
  { artist: 'Bajaga i Instruktori', title: 'Godine prolaze', year: 1988 },
  { artist: 'Bajaga i Instruktori', title: 'Moji drugovi', year: 1996 },
  { artist: 'Bajaga i Instruktori', title: 'Plavi safir', year: 1988 },
  { artist: 'Bajaga i Instruktori', title: 'Tamara', year: 1984 },
  { artist: 'Bajaga i Instruktori', title: 'Zažmuri', year: 1985 },
  { artist: 'Bajaga i Instruktori', title: 'Sa druge strane jastuka', year: 1985 },
  { artist: 'Bajaga i Instruktori', title: '220 u voltima', year: 1985 },
  { artist: 'EKV', title: 'Kao da je bilo nekad', year: 1986 },
  { artist: 'EKV', title: 'Ti si sav moj bol', year: 1986 },
  { artist: 'EKV', title: 'Srce', year: 1989 },
  { artist: 'EKV', title: 'Par godina za nas', year: 1989 },
  { artist: 'EKV', title: 'Krug', year: 1989 },
  { artist: 'EKV', title: 'Oči boje meda', year: 1985 },
  { artist: 'Parni Valjak', title: 'Sve još miriše na nju', year: 1993 },
  { artist: 'Parni Valjak', title: 'Jesen u meni', year: 1987 },
  { artist: 'Parni Valjak', title: 'Ugasi me', year: 1985 },
  { artist: 'Parni Valjak', title: 'Dođi', year: 1993 },
  { artist: 'Parni Valjak', title: 'Lutka za bal', year: 1977 },
  { artist: 'Parni Valjak', title: 'Stranica dnevnika', year: 1979 },
  { artist: 'Prljavo Kazalište', title: 'Marina', year: 1988 },
  { artist: 'Prljavo Kazalište', title: 'Mojoj majci (Ruža hrvatska)', year: 1988 },
  { artist: 'Prljavo Kazalište', title: 'Crno bijeli svijet', year: 1980 },
  { artist: 'Prljavo Kazalište', title: 'Mi plešemo', year: 1980 },
  { artist: 'Prljavo Kazalište', title: 'Kiše jesenje', year: 1993 },
  { artist: 'Prljavo Kazalište', title: 'Zaustavite zemlju', year: 1988 },
  { artist: 'Crvena Jabuka', title: 'Nekako s proljeća', year: 1991 },
  { artist: 'Crvena Jabuka', title: 'Tamo gde ljubav počinje', year: 1989 },
  { artist: 'Crvena Jabuka', title: 'Tuga, ti i ja', year: 1987 },
  { artist: 'Crvena Jabuka', title: 'To mi radi', year: 1989 },
  { artist: 'Crvena Jabuka', title: 'Bježi kišo s prozora', year: 1986 },
  { artist: 'Crvena Jabuka', title: 'Dirlija', year: 1986 },
  { artist: 'Plavi Orkestar', title: 'Bolje biti pijan nego star', year: 1985 },
  { artist: 'Plavi Orkestar', title: 'Suada', year: 1985 },
  { artist: 'Plavi Orkestar', title: 'Od rođendana do rođendana', year: 1989 },
  { artist: 'Plavi Orkestar', title: 'Sava tiho teče', year: 1986 },
  { artist: 'Plavi Orkestar', title: 'Goodbye Teens', year: 1985 },
  { artist: 'Zabranjeno Pušenje', title: 'Zenica Blues', year: 1984 },
  { artist: 'Zabranjeno Pušenje', title: 'Balada o Pišonji i Žugi', year: 1987 },
  { artist: 'Zabranjeno Pušenje', title: 'Fikreta (Poso, kuća, birtija)', year: 1987 },
  { artist: 'Zabranjeno Pušenje', title: 'Ibro dirka', year: 1985 },
  { artist: 'Zabranjeno Pušenje', title: 'Hadžija il bos', year: 1987 },
  { artist: 'Divlje Jagode', title: 'Jedina moja', year: 1977 },
  { artist: 'Divlje Jagode', title: 'Krivo je more', year: 1977 },
  { artist: 'Divlje Jagode', title: 'Motori', year: 1982 },
  { artist: 'Divlje Jagode', title: 'Kap po kap', year: 1994 },
  { artist: 'Indexi', title: 'Bacila je sve niz rijeku', year: 1974 },
  { artist: 'Indexi', title: 'Da sam ja netko', year: 1970 },
  { artist: 'Indexi', title: 'Sanjam', year: 1971 },
  { artist: 'Indexi', title: 'Plima', year: 1973 },
  { artist: 'Indexi', title: 'Jutro će promijeniti sve', year: 1968 },
  { artist: 'YU Grupa', title: 'Crni leptir', year: 1973 },
  { artist: 'YU Grupa', title: 'Čudna šuma', year: 1973 },
  { artist: 'YU Grupa', title: 'Od zlata jabuka', year: 1987 },
  { artist: 'YU Grupa', title: 'Mornar', year: 1988 },
  { artist: 'Smak', title: 'Daire', year: 1977 },
  { artist: 'Smak', title: 'Crna dama', year: 1977 },
  { artist: 'Smak', title: 'Profesor', year: 1977 },
  { artist: 'Smak', title: 'Biska 2', year: 1975 },
  { artist: 'Kerber', title: 'Ratne igre', year: 1986 },
  { artist: 'Kerber', title: 'Bolje da sam druge ljubio', year: 1986 },
  { artist: 'Kerber', title: 'Seobe', year: 1986 },
  { artist: 'Kerber', title: 'Mama, tata', year: 1988 },
  { artist: 'Galija', title: 'Dodirni me', year: 1994 },
  { artist: 'Galija', title: 'Digni ruku', year: 1986 },
  { artist: 'Galija', title: 'Skadarska', year: 1991 },
  { artist: 'Galija', title: 'Kotor', year: 1997 },
  { artist: 'Galija', title: 'Stare trube', year: 1991 },
  { artist: 'Električni Orgazam', title: 'Igra rokenrol cela Jugoslavija', year: 1988 },
  { artist: 'Električni Orgazam', title: 'Zlatni papagaj', year: 1980 },
  { artist: 'Električni Orgazam', title: 'Bejbe, ti nisi tu', year: 1986 },
  { artist: 'Električni Orgazam', title: 'Nebo', year: 1981 },
  { artist: 'Idoli', title: 'Maljčiki', year: 1981 },
  { artist: 'Idoli', title: 'Retko te viđam sa devojkama', year: 1980 },
  { artist: 'Idoli', title: 'Rusija', year: 1982 },
  { artist: 'Idoli', title: 'Kenozoik', year: 1982 },
  { artist: 'Film', title: 'Zamisli život u ritmu muzike za ples', year: 1981 },
  { artist: 'Film', title: 'Sjećam se prvog poljupca', year: 1987 },
  { artist: 'Film', title: 'Pjevajmo do zore', year: 1981 },
  { artist: 'Film', title: 'Boje su u nama', year: 1983 },
  { artist: 'Haustor', title: 'Šejn', year: 1985 },
  { artist: 'Haustor', title: 'Ena', year: 1985 },
  { artist: 'Haustor', title: 'Moja prva ljubav', year: 1981 },
  { artist: 'Haustor', title: 'Uzalud pitaš', year: 1987 },
  { artist: 'Azra', title: 'Balkan', year: 1979 },
  { artist: 'Azra', title: 'A šta da radim', year: 1979 },
  { artist: 'Azra', title: 'Obrati pažnju na posljednju stvar', year: 1980 },
  { artist: 'Azra', title: 'Krvava Meri', year: 1981 },
  { artist: 'Azra', title: 'Marina', year: 1980 },
  { artist: 'Azra', title: 'Uradi nešto', year: 1980 },
  { artist: 'Atomsko Sklonište', title: 'Za ljubav treba imat dušu', year: 1982 },
  { artist: 'Atomsko Sklonište', title: 'Treba imat dušu', year: 1982 },
  { artist: 'Atomsko Sklonište', title: 'Žuti kišobran', year: 1980 },
  { artist: 'Partibrejkers', title: '1000 godina', year: 1984 },
  { artist: 'Partibrejkers', title: 'Kreni prema meni', year: 1989 },
  { artist: 'Partibrejkers', title: 'Hoću da znam', year: 1994 },
  { artist: 'Partibrejkers', title: 'Hipnotisana gomila', year: 1989 },
  { artist: 'Psihomodo Pop', title: 'Ja volim samo sebe', year: 1988 },
  { artist: 'Psihomodo Pop', title: 'Frida', year: 1992 },
  { artist: 'Psihomodo Pop', title: 'Donna', year: 2014 },
  { artist: 'Đavoli', title: 'Stojin na kantunu', year: 1986 },
  { artist: 'Đavoli', title: 'Pričaj mi o ljubavi', year: 1986 },
  { artist: 'Đavoli', title: 'Jagode i čokolada', year: 1988 },
  { artist: 'Đorđe Balašević', title: 'D-moll', year: 1989 },
  { artist: 'Đorđe Balašević', title: 'Svirajte mi jesen stiže dunjo moja', year: 1983 },
  { artist: 'Đorđe Balašević', title: 'Priča o Vasi Ladačkom', year: 1980 },
  { artist: 'Đorđe Balašević', title: 'Ringišpil', year: 1991 },
  { artist: 'Đorđe Balašević', title: 'Lepota je prokleta', year: 1996 },
  { artist: 'Đorđe Balašević', title: 'Boža zvani Pub', year: 1982 },
  { artist: 'Đorđe Balašević', title: 'Slovenska', year: 1985 },
  { artist: 'Đorđe Balašević', title: 'Ne lomite mi bagrenje', year: 1986 },
  { artist: 'Oliver Dragojević', title: 'Cesarica', year: 1993 },
  { artist: 'Oliver Dragojević', title: 'Oprosti mi pape', year: 1978 },
  { artist: 'Oliver Dragojević', title: 'Galeb i ja', year: 1975 },
  { artist: 'Oliver Dragojević', title: 'Nadalina', year: 1980 },
  { artist: 'Oliver Dragojević', title: 'Trag u beskraju', year: 2002 },
  { artist: 'Gibonni', title: 'Libar', year: 2001 },
  { artist: 'Gibonni', title: 'Mirakul', year: 2001 },
  { artist: 'Gibonni', title: 'Oprosti', year: 2001 },
  { artist: 'Gibonni', title: 'Činim pravu stvar', year: 1999 },
  { artist: 'Dino Merlin', title: 'Moj je život Švicarska', year: 2000 },
  { artist: 'Dino Merlin', title: 'Godinama', year: 2000 },
  { artist: 'Dino Merlin', title: 'Kad si rekla da me voliš', year: 2000 },
  { artist: 'Dino Merlin', title: 'Deset mlađa', year: 2008 },
  { artist: 'Dino Merlin', title: 'Nedostaješ', year: 2008 },
  { artist: 'Dino Merlin', title: 'Sve je laž', year: 2000 },
  { artist: 'Dino Merlin', title: 'Bosnom behar probeharao', year: 1989 },
  { artist: 'Hari Mata Hari', title: 'Lejla', year: 2006 },
  { artist: 'Hari Mata Hari', title: 'Strah me da te volim', year: 1990 },
  { artist: 'Hari Mata Hari', title: 'Prsten i zlatni lanac', year: 1989 },
  { artist: 'Hari Mata Hari', title: 'Kao kokos', year: 1999 },
  { artist: 'Hari Mata Hari', title: 'Baš ti lijepo stoje suze', year: 2001 },
  { artist: 'Magazin', title: 'Kokolo', year: 1983 },
  { artist: 'Magazin', title: 'Ti si želja mog života', year: 1987 },
  { artist: 'Magazin', title: 'Ginem', year: 1998 },
  { artist: 'Magazin', title: 'Minus i plus', year: 2000 },
  { artist: 'Magazin', title: 'Sve bi seke ljubile mornare', year: 1987 },
  { artist: 'Magazin', title: 'Gutljaj vina', year: 1998 },
  { artist: 'Novi Fosili', title: 'Za dobra stara vremena', year: 1987 },
  { artist: 'Novi Fosili', title: 'Ja sam za ples', year: 1987 },
  { artist: 'Novi Fosili', title: 'Košulja plava', year: 1981 },
  { artist: 'Novi Fosili', title: 'Milena', year: 1983 },
  { artist: 'Srebrna Krila', title: 'O, Ana', year: 1978 },
  { artist: 'Srebrna Krila', title: 'Zakuni se ljubavi', year: 1979 },
  { artist: 'Boris Novković', title: 'Tamara', year: 1986 },
  { artist: 'Boris Novković', title: 'Dok svira radio', year: 1988 },
  { artist: 'Vlado Georgiev', title: 'Jedina', year: 2003 },
  { artist: 'Vlado Georgiev', title: 'Žena kao ti', year: 2003 },
  { artist: 'Vlado Georgiev', title: 'Anđele', year: 2001 },
  { artist: 'Vlado Georgiev', title: 'Nisam ljubomoran', year: 2003 },
  { artist: 'Željko Joksimović', title: 'Lane moje', year: 2004 },
  { artist: 'Željko Joksimović', title: 'Nije ljubav stvar', year: 2012 },
  { artist: 'Željko Joksimović', title: 'Leđa o leđa', year: 2003 },
  { artist: 'Željko Joksimović', title: 'Supermen', year: 2004 },
  { artist: 'Toše Proeski', title: 'Čija si', year: 2003 },
  { artist: 'Toše Proeski', title: 'Srce nije kamen', year: 2006 },
  { artist: 'Toše Proeski', title: 'Bože, brani je od zla', year: 2007 },
  { artist: 'Toše Proeski', title: 'Igra bez granica', year: 2007 },
  { artist: 'Toše Proeski', title: 'Ko ti to grize obraze', year: 2005 },
  { artist: 'Van Gogh', title: 'Neko te ima noćas', year: 1993 },
  { artist: 'Van Gogh', title: 'Kolo (Ludo luda)', year: 2006 },
  { artist: 'Van Gogh', title: 'Spisak razloga', year: 2006 },
  { artist: 'Van Gogh', title: 'Brod od papira', year: 1999 },
  { artist: 'Neverne Bebe', title: 'Tužna pesma', year: 2004 },
  { artist: 'Neverne Bebe', title: 'Dvoje', year: 2001 },
  { artist: 'Neverne Bebe', title: 'Veliki je Bog', year: 2004 },
  { artist: 'Zana', title: 'Dodirni mi kolena', year: 1982 },
  { artist: 'Zana', title: 'Mladiću moj', year: 1983 },
  { artist: 'Zana', title: 'Vejte snegovi', year: 1987 },
  { artist: 'Zana', title: 'Oženićeš se ti', year: 1991 },
  { artist: 'Viktorija', title: 'Daj, ne pitaj', year: 1988 },
  { artist: 'Viktorija', title: 'Rat i mir', year: 1990 },
  { artist: 'Viktorija', title: 'Barakuda', year: 1990 },
  { artist: 'Poslednja Igra Leptira', title: 'Nataša', year: 1982 },
  { artist: 'Poslednja Igra Leptira', title: 'Grudi balkanske', year: 1985 },
  { artist: 'Poslednja Igra Leptira', title: 'Dečko, ajde ohladi', year: 1986 },
  { artist: 'Dubioza Kolektiv', title: 'Kažu', year: 2013 },
  { artist: 'Dubioza Kolektiv', title: 'Blam', year: 2008 },
  { artist: 'Dubioza Kolektiv', title: 'Firma Ilegal', year: 2008 },
  { artist: 'S.A.R.S.', title: 'Lutka', year: 2013 },
  { artist: 'S.A.R.S.', title: 'Buđav lebac', year: 2009 },
  { artist: 'S.A.R.S.', title: 'Perspektiva', year: 2011 },
  { artist: 'Đorđe Balašević', title: 'Devojka sa čardaš nogama', year: 1989 },
  { artist: 'Đorđe Balašević', title: 'Al\' se nekad dobro jelo', year: 1982 },
  { artist: 'Đorđe Balašević', title: 'Olivera', year: 1985 },
  { artist: 'Đorđe Balašević', title: 'Ne volim januar', year: 1986 },
  { artist: 'Đorđe Balašević', title: 'Mirka', year: 1980 },
  { artist: 'Đorđe Balašević', title: 'Odlazi cirkus', year: 1980 },
  { artist: 'Riblja Čorba', title: 'Avionu slomiću ti krila', year: 1986 },
  { artist: 'Riblja Čorba', title: 'Dobro jutro', year: 1982 },
  { artist: 'Riblja Čorba', title: 'Evo ti za taksi', year: 1989 },
  { artist: 'Bijelo Dugme', title: 'Pristao sam biću sve što hoće', year: 1979 },
  { artist: 'Bijelo Dugme', title: 'Te noći kad umrem', year: 1986 },
  { artist: 'Bijelo Dugme', title: 'Ne gledaj me tako', year: 1975 },
  { artist: 'Zdravko Čolić', title: 'Produži dalje', year: 1977 },
  { artist: 'Zdravko Čolić', title: 'Sinoć nisi bila tu', year: 1972 },
  { artist: 'Zdravko Čolić', title: 'Maslinasto zelena', year: 1984 },
  { artist: 'Zdravko Čolić', title: 'Čini mi se grmi', year: 1988 },
  { artist: 'Zdravko Čolić', title: 'April u Beogradu', year: 1975 },
  { artist: 'Bajaga i Instruktori', title: 'Muzika na struju', year: 1993 },
  { artist: 'Bajaga i Instruktori', title: 'Ruski voz', year: 1988 },
  { artist: 'Bajaga i Instruktori', title: 'Verujem, ne verujem', year: 1988 },
  { artist: 'Bajaga i Instruktori', title: 'Dobro jutro džezeri', year: 1985 },
  { artist: 'EKV', title: 'Zemlja', year: 1987 },
  { artist: 'EKV', title: 'Radostan dan', year: 1984 },
  { artist: 'EKV', title: 'Dum dum', year: 1991 },
  { artist: 'Zabranjeno Pušenje', title: 'Nedelja kad je otišo Hase', year: 1985 },
  { artist: 'Zabranjeno Pušenje', title: 'Guzonjin sin', year: 1989 },
  { artist: 'Zabranjeno Pušenje', title: 'Možeš imat moje tijelo', year: 1997 },
  { artist: 'Prljavo Kazalište', title: 'Heroj ulice', year: 1981 },
  { artist: 'Prljavo Kazalište', title: 'Sve je lako kad si mlad', year: 1983 },
  { artist: 'Prljavo Kazalište', title: 'Tu noć kad si se udavala', year: 1993 },
  { artist: 'Parni Valjak', title: 'Moja je pjesma lagana', year: 1988 },
  { artist: 'Parni Valjak', title: 'Uhvati ritam', year: 1984 },
  { artist: 'Parni Valjak', title: 'Neda', year: 1980 },
  { artist: 'Crvena Jabuka', title: 'Sa tvojih usana', year: 1986 },
  { artist: 'Crvena Jabuka', title: 'Sviđa mi se ova stvar', year: 1988 },
  { artist: 'Crvena Jabuka', title: 'Zovu nas ulice', year: 1987 },
  { artist: 'Plavi Orkestar', title: 'Ako su to samo bile laži', year: 1998 },
  { artist: 'Plavi Orkestar', title: 'Lovac i košuta', year: 1998 },
  { artist: 'Dino Merlin', title: 'Danas sam OK', year: 1995 },
  { artist: 'Dino Merlin', title: 'Supermen', year: 2004 },
  { artist: 'Dino Merlin', title: 'Ruža', year: 2014 },
  { artist: 'Dino Merlin', title: 'Rane', year: 2014 },
  { artist: 'Oliver Dragojević', title: 'Molitva za Magdalenu', year: 1978 },
  { artist: 'Oliver Dragojević', title: 'Skalinada', year: 1976 },
  { artist: 'Oliver Dragojević', title: 'Vjeruj u ljubav', year: 1979 },
  { artist: 'Gibonni', title: 'Tempera', year: 1994 },
  { artist: 'Gibonni', title: 'Zlatne godine', year: 1993 },
  { artist: 'Gibonni', title: 'Posoljeni zrak i razlivena tinta', year: 2001 },
  { artist: 'Toše Proeski', title: 'Pratim te', year: 2005 },
  { artist: 'Toše Proeski', title: 'Tajno moja', year: 2000 },
  { artist: 'Toše Proeski', title: 'Soba za tugu', year: 2002 },
  { artist: 'Toše Proeski', title: 'Ledena', year: 2002 },
  { artist: 'Vlado Georgiev', title: 'Reci mi da znam', year: 2001 },
  { artist: 'Vlado Georgiev', title: 'Sam protiv svih', year: 2003 },
  { artist: 'Željko Joksimović', title: 'Devojka sa polja zelenih', year: 2002 },
  { artist: 'Željko Joksimović', title: 'Vreteno', year: 2001 },
  { artist: 'Željko Joksimović', title: 'Ljubavi', year: 2009 },
  { artist: 'Saša Kovačević', title: 'Lapsus', year: 2012 },
  { artist: 'Saša Kovačević', title: 'Slučajno', year: 2013 },
  { artist: 'Saša Kovačević', title: 'Ruka za spas', year: 2006 },
  { artist: 'Saša Kovačević', title: 'Temperatura', year: 2016 },
  { artist: 'Sergej Ćetković', title: 'Pogledi u tami', year: 2005 },
  { artist: 'Sergej Ćetković', title: 'Zaustaviću vrijeme', year: 2000 },
  { artist: 'Sergej Ćetković', title: 'Prokleta bila', year: 2003 },
  { artist: 'Toni Cetinski', title: 'Blago onom tko te ima', year: 2001 },
  { artist: 'Toni Cetinski', title: 'Onaj tko te ljubi sretan je', year: 2003 },
  { artist: 'Toni Cetinski', title: 'Kad žena zavoli', year: 2005 },
  { artist: 'Nina Badrić', title: 'Čarobno jutro', year: 2003 },
  { artist: 'Nina Badrić', title: 'Dani i godine', year: 2016 },
  { artist: 'Nina Badrić', title: 'Takvi kao ti', year: 2003 },
  { artist: 'Petar Grašo', title: 'Ko nam brani', year: 1999 },
  { artist: 'Petar Grašo', title: 'Utorak', year: 1999 },
  { artist: 'Petar Grašo', title: 'Ako te pitaju', year: 2017 },
  { artist: 'Petar Grašo', title: 'Moje zlato', year: 2015 },
  { artist: 'Massimo', title: 'Iz jednog pogleda', year: 2011 },
  { artist: 'Massimo', title: 'Suze nam stale na put', year: 2013 },
  { artist: 'Massimo', title: 'Stranac u noći', year: 1987 },
  { artist: 'Josipa Lisac', title: 'Magla', year: 1980 },
  { artist: 'Josipa Lisac', title: 'O jednoj mladosti', year: 1973 },
  { artist: 'Josipa Lisac', title: 'Gdje Dunav ljubi nebo', year: 1987 },
  { artist: 'Oliver Mandić', title: 'Osloni se na mene', year: 1978 },
  { artist: 'Oliver Mandić', title: 'Pitaju me, pitaju', year: 1982 },
  { artist: 'Oliver Mandić', title: 'Pomagajte drugovi', year: 1985 },
  { artist: 'Leb i Sol', title: 'Čuvam noć od budnih', year: 1987 },
  { artist: 'Leb i Sol', title: 'Kao kakao', year: 1987 },
  { artist: 'Hladno Pivo', title: 'Samo za taj osjećaj', year: 2002 },
  { artist: 'Hladno Pivo', title: 'Nije sve tako sivo', year: 2007 },
  { artist: 'Let 3', title: 'Mama ŠČ!', year: 2023 },
  { artist: 'Neno Belan', title: 'Rijeka snova', year: 2007 }
];

// 3. Expanded Moderno & Trap & IDJ (2016-2026 trending hits)
const MODERNO_ITEMS = [
  { artist: 'Voyage', title: 'Kartel', year: 2021 },
  { artist: 'Voyage', title: 'Pleši', year: 2021 },
  { artist: 'Voyage', title: 'Euforija', year: 2021 },
  { artist: 'Voyage', title: 'Detinjstvo', year: 2022 },
  { artist: 'Voyage', title: 'Tango', year: 2022 },
  { artist: 'Voyage', title: 'La La La', year: 2023 },
  { artist: 'Voyage', title: 'Balerina', year: 2023 },
  { artist: 'Voyage & Nucci', title: 'Bella Hadid', year: 2023 },
  { artist: 'Voyage & Nucci', title: 'Balkan', year: 2021 },
  { artist: 'Voyage & Nucci', title: 'Gad', year: 2022 },
  { artist: 'Nucci', title: 'Uđi na WA', year: 2020 },
  { artist: 'Nucci', title: 'Bebo', year: 2021 },
  { artist: 'Nucci', title: 'Vroom', year: 2021 },
  { artist: 'Nucci', title: 'Crno oko', year: 2022 },
  { artist: 'Nucci', title: 'Automatti', year: 2023 },
  { artist: 'Nucci', title: 'Đerdan', year: 2022 },
  { artist: 'Nucci', title: 'Opanci', year: 2022 },
  { artist: 'Breskvica', title: 'Bonvoyage', year: 2021 },
  { artist: 'Breskvica', title: 'Leptir', year: 2022 },
  { artist: 'Breskvica', title: 'Loš', year: 2022 },
  { artist: 'Breskvica', title: 'Gnezdo orlovo', year: 2024 },
  { artist: 'Breskvica', title: 'Kume moj', year: 2023 },
  { artist: 'Breskvica', title: 'Do gole kože', year: 2023 },
  { artist: 'Aleksandra Prijović', title: 'Legitimno', year: 2020 },
  { artist: 'Aleksandra Prijović', title: 'Bogata sirotinja', year: 2019 },
  { artist: 'Aleksandra Prijović', title: 'Dam Dam Dam', year: 2023 },
  { artist: 'Aleksandra Prijović', title: 'Psiho', year: 2023 },
  { artist: 'Aleksandra Prijović', title: 'Ja sam odlično', year: 2022 },
  { artist: 'Aleksandra Prijović', title: 'Klizav pod', year: 2017 },
  { artist: 'Aleksandra Prijović', title: 'Testament', year: 2017 },
  { artist: 'Aleksandra Prijović', title: 'Zvuk tišine', year: 2022 },
  { artist: 'Aleksandra Prijović', title: 'Sve po starom', year: 2023 },
  { artist: 'Aleksandra Prijović', title: 'Kuća strave', year: 2023 },
  { artist: 'Tea Tairović', title: 'Hajde', year: 2021 },
  { artist: 'Tea Tairović', title: 'Balerina', year: 2023 },
  { artist: 'Tea Tairović', title: 'Dva i dva', year: 2022 },
  { artist: 'Tea Tairović', title: 'Balkanija', year: 2022 },
  { artist: 'Tea Tairović', title: 'Boy Boy', year: 2023 },
  { artist: 'Tea Tairović', title: 'Izrael i Palestina', year: 2023 },
  { artist: 'Tea Tairović', title: 'Na jednu noć', year: 2021 },
  { artist: 'Tea Tairović', title: 'Dubai', year: 2022 },
  { artist: 'Tea Tairović', title: 'Pozovi', year: 2024 },
  { artist: 'Tea Tairović', title: 'Tea', year: 2024 },
  { artist: 'Jala Brat & Buba Corelli', title: 'Klinka', year: 2016 },
  { artist: 'Jala Brat & Buba Corelli', title: 'Ultimatum', year: 2017 },
  { artist: 'Jala Brat & Buba Corelli', title: 'Mafia', year: 2018 },
  { artist: 'Jala Brat & Buba Corelli', title: 'Kamikaza', year: 2019 },
  { artist: 'Jala Brat & Buba Corelli', title: 'O.D.D.D.', year: 2019 },
  { artist: 'Jala Brat & Buba Corelli', title: 'Zove Vienna', year: 2019 },
  { artist: 'Jala Brat & Buba Corelli', title: 'Karantin', year: 2020 },
  { artist: 'Jala Brat & Buba Corelli', title: 'Monster', year: 2022 },
  { artist: 'Jala Brat', title: 'Mlada i luda', year: 2018 },
  { artist: 'Jala Brat', title: 'Gasira', year: 2019 },
  { artist: 'Jala Brat', title: 'Adrenalina', year: 2022 },
  { artist: 'Buba Corelli', title: 'Balenciaga', year: 2018 },
  { artist: 'Buba Corelli', title: 'Irina Shayk', year: 2019 },
  { artist: 'Buba Corelli', title: 'Divljam', year: 2021 },
  { artist: 'Buba Corelli', title: 'Je l\' me voliš', year: 2022 },
  { artist: 'Rasta', title: 'Kavali', year: 2015 },
  { artist: 'Rasta', title: 'Euforija', year: 2016 },
  { artist: 'Rasta', title: 'Kamasutra', year: 2017 },
  { artist: 'Rasta', title: 'Mantra', year: 2019 },
  { artist: 'Rasta', title: 'Adio Amore', year: 2017 },
  { artist: 'Rasta', title: 'Benz ili Bimmer', year: 2019 },
  { artist: 'Rasta', title: 'Gatling', year: 2023 },
  { artist: 'Devito', title: 'Uh', year: 2020 },
  { artist: 'Devito', title: 'Vudu', year: 2020 },
  { artist: 'Devito', title: 'Mame mi', year: 2021 },
  { artist: 'Devito', title: 'Marina', year: 2022 },
  { artist: 'Devito', title: 'Omađijala', year: 2022 },
  { artist: 'Devito', title: 'Leden', year: 2021 },
  { artist: 'Devito', title: 'Rolex', year: 2023 },
  { artist: 'Desingerica & Pljugica', title: 'Ccokolada', year: 2023 },
  { artist: 'Desingerica & Pljugica', title: 'Merccedecc', year: 2023 },
  { artist: 'Desingerica & Pljugica', title: 'Pola pet', year: 2023 },
  { artist: 'Desingerica', title: 'Čoko', year: 2023 },
  { artist: 'Desingerica', title: 'Skakavac', year: 2024 },
  { artist: 'Desingerica', title: 'Rendalicca', year: 2024 },
  { artist: 'Desingerica', title: 'Penjadita', year: 2024 },
  { artist: 'Relja', title: 'Beograd još živi', year: 2015 },
  { artist: 'Relja', title: 'Adrenalina', year: 2017 },
  { artist: 'Relja', title: 'Made in Balkan', year: 2019 },
  { artist: 'Relja', title: 'Princeza na belom', year: 2020 },
  { artist: 'Relja', title: 'Genge', year: 2020 },
  { artist: 'Relja & Nucci', title: 'Zovite doktore', year: 2022 },
  { artist: 'Nikolija', title: 'Opasna igra', year: 2015 },
  { artist: 'Nikolija', title: 'Nakit', year: 2022 },
  { artist: 'Nikolija', title: 'Pilot', year: 2023 },
  { artist: 'Nikolija', title: 'Nema limita', year: 2018 },
  { artist: 'Teodora Džehverović', title: 'Tresi tresi', year: 2019 },
  { artist: 'Teodora Džehverović', title: 'Kristijan Grej', year: 2017 },
  { artist: 'Teodora Džehverović', title: 'Gasolina', year: 2020 },
  { artist: 'Teodora Džehverović', title: 'Vudu', year: 2020 },
  { artist: 'Teodora Džehverović', title: 'Aventador', year: 2022 },
  { artist: 'Teodora Džehverović', title: 'Polumesec', year: 2023 },
  { artist: 'Cobi', title: 'Biseri iz blata', year: 2019 },
  { artist: 'Cobi', title: 'Leto je', year: 2020 },
  { artist: 'Cobi', title: 'Zlatno dete', year: 2021 },
  { artist: 'Cobi', title: 'Odakle sam ja', year: 2020 },
  { artist: 'Senidah', title: 'Slađana', year: 2018 },
  { artist: 'Senidah', title: 'Mišići', year: 2019 },
  { artist: 'Senidah', title: 'Kamikaza', year: 2019 },
  { artist: 'Senidah', title: 'Replay', year: 2021 },
  { artist: 'Senidah', title: 'Behute', year: 2022 },
  { artist: 'Senidah', title: 'Dva prsta', year: 2022 },
  { artist: 'Sara Jo', title: 'Muškarčina', year: 2022 },
  { artist: 'Sara Jo', title: 'Bez sna', year: 2019 },
  { artist: 'Sara Jo', title: 'Mili, mili', year: 2019 },
  { artist: 'Sara Jo', title: 'Divlja', year: 2021 },
  { artist: 'Zera', title: 'Do zore', year: 2021 },
  { artist: 'Zera', title: 'Baraba', year: 2022 },
  { artist: 'Zera', title: 'Kalaši', year: 2022 },
  { artist: 'Zera', title: 'Ccuti', year: 2023 },
  { artist: 'Barbara Bobak', title: 'Duplo gora', year: 2022 },
  { artist: 'Barbara Bobak', title: 'Lažeš me ljubavi', year: 2023 },
  { artist: 'Barbara Bobak', title: 'Prva do zida', year: 2023 },
  { artist: 'Sanja Vučić', title: 'Omađijan', year: 2022 },
  { artist: 'Sanja Vučić', title: 'Đerdan', year: 2022 },
  { artist: 'Sanja Vučić', title: 'Remek-delo', year: 2023 },
  { artist: 'Gazda Paja', title: 'Čke beogradske', year: 2012 },
  { artist: 'Gazda Paja', title: 'Dizel', year: 2020 },
  { artist: 'Gazda Paja', title: 'Ausländer', year: 2019 },
  { artist: 'Gazda Paja', title: 'Pronto', year: 2021 },
  { artist: 'Fox', title: 'Šurim bika', year: 2017 },
  { artist: 'Fox', title: 'Indigo deca', year: 2018 },
  { artist: 'Fox', title: 'Par dana', year: 2019 },
  { artist: 'Surreal', title: 'Ja sam u gasu', year: 2018 },
  { artist: 'Surreal', title: 'Sve pare', year: 2019 },
  { artist: 'Surreal', title: 'Zadnji ples', year: 2021 },
  { artist: 'Corona & Rimski', title: 'Geto princeza', year: 2016 },
  { artist: 'Corona & Rimski', title: 'Oči boje viskija', year: 2017 },
  { artist: 'Corona & Rimski', title: 'Volećeš me sutra', year: 2018 },
  { artist: 'Corona & Rimski', title: 'Tajne', year: 2020 },
  { artist: 'Crni Cerak', title: 'CC1', year: 2021 },
  { artist: 'Crni Cerak', title: 'CC2', year: 2022 },
  { artist: 'Crni Cerak', title: 'CC3', year: 2023 },
  { artist: 'Crni Cerak', title: 'Dva telefona', year: 2022 },
  { artist: 'Sajfer', title: 'Karneval', year: 2022 },
  { artist: 'Sajfer', title: 'Ignor', year: 2023 },
  { artist: 'Sajfer', title: 'Medikament', year: 2023 },
  { artist: 'Seksi', title: 'Kola', year: 2021 },
  { artist: 'Mili', title: 'Grmi', year: 2019 },
  { artist: 'Mili', title: 'Loca', year: 2020 },
  { artist: 'THCF', title: 'Ideš za Kanadu', year: 2015 },
  { artist: 'THCF', title: 'Krvavi Balkan', year: 2017 },
  { artist: 'Klinac', title: 'U sumrak', year: 2019 },
  { artist: 'Klinac', title: 'Sve', year: 2019 },
  { artist: 'Klinac', title: 'Nemam mira', year: 2020 },
  { artist: 'Grše', title: 'Mamma Mia', year: 2023 },
  { artist: 'Grše', title: 'Sip', year: 2023 },
  { artist: 'Grše', title: 'Fantazija', year: 2024 },
  { artist: 'Miach & Grše', title: 'Led', year: 2023 },
  { artist: 'Hiljson Mandela', title: 'Cura s kvarta', year: 2022 },
  { artist: 'Hiljson Mandela', title: 'Neće k**ac', year: 2022 },
  { artist: 'Henny', title: 'Bratz', year: 2022 },
  { artist: 'Henny', title: 'Sava i Dunav', year: 2022 },
  { artist: 'Popov', title: 'Miki miki', year: 2022 },
  { artist: 'Inas', title: 'Da da da', year: 2020 },
  { artist: 'Inas', title: 'Speedy Gonzales', year: 2021 },
  { artist: 'Amna', title: 'Lagana', year: 2022 },
  { artist: 'Albino', title: 'Glas u tami', year: 2022 },
  { artist: 'Teya Dora', title: 'Džanum', year: 2023 },
  { artist: 'Teya Dora', title: 'Ramonda', year: 2024 },
  { artist: 'Konstrakta', title: 'In Corpore Sano', year: 2022 },
  { artist: 'Buč Kesidi', title: 'Nema ljubavi u klubu', year: 2019 },
  { artist: 'Buč Kesidi', title: 'TIHO', year: 2019 },
  { artist: 'Buč Kesidi', title: 'Euforija', year: 2019 },
  { artist: 'Mimi Mercedez', title: 'Patike za trčanje', year: 2015 },
  { artist: 'Mimi Mercedez', title: 'Ne možeš sa nama', year: 2016 },
  { artist: 'Mimi Mercedez', title: 'Dajive komi', year: 2022 },
  { artist: 'Smoke Mardeljano', title: 'Ja repujem', year: 2015 },
  { artist: 'Nucci', title: 'Vrelo', year: 2021 },
  { artist: 'Nucci', title: 'Localo', year: 2021 },
  { artist: 'Nucci', title: 'Sve zbog nje', year: 2023 },
  { artist: 'Nucci', title: 'Chupakabra', year: 2024 },
  { artist: 'Voyage', title: 'Trebaš li me', year: 2022 },
  { artist: 'Voyage', title: 'Bounce', year: 2022 },
  { artist: 'Voyage', title: 'Periferija', year: 2023 },
  { artist: 'Voyage', title: 'Amsterdam', year: 2023 },
  { artist: 'Breskvica', title: 'Mala', year: 2022 },
  { artist: 'Breskvica', title: 'Bad Boy', year: 2023 },
  { artist: 'Breskvica', title: 'Srećan put', year: 2021 },
  { artist: 'Aleksandra Prijović', title: 'Senke', year: 2016 },
  { artist: 'Aleksandra Prijović', title: 'Totalna anestezija', year: 2016 },
  { artist: 'Aleksandra Prijović', title: 'Devet života', year: 2023 },
  { artist: 'Aleksandra Prijović', title: 'Prvi si počeo', year: 2023 },
  { artist: 'Tea Tairović', title: 'Plakalo leto', year: 2022 },
  { artist: 'Tea Tairović', title: 'Top', year: 2022 },
  { artist: 'Tea Tairović', title: 'Ime mi je ljubav', year: 2024 },
  { artist: 'Tea Tairović', title: 'Keramičar', year: 2024 },
  { artist: 'Devito', title: 'Aligatori', year: 2020 },
  { artist: 'Devito', title: 'Flex', year: 2021 },
  { artist: 'Devito', title: 'Tajne', year: 2022 },
  { artist: 'Desingerica', title: 'Ccrno', year: 2023 },
  { artist: 'Desingerica', title: 'Tuckavacc', year: 2023 },
  { artist: 'Desingerica', title: 'Baxuz', year: 2024 },
  { artist: 'Rasta', title: 'Taktika', year: 2018 },
  { artist: 'Rasta', title: 'Kavasaki', year: 2014 },
  { artist: 'Rasta', title: 'Hotel', year: 2017 },
  { artist: 'Jala Brat', title: 'Partijam', year: 2019 },
  { artist: 'Jala Brat', title: 'Casino', year: 2020 },
  { artist: 'Jala Brat', title: 'Dostojevski', year: 2021 },
  { artist: 'Buba Corelli', title: 'Spartanac', year: 2018 },
  { artist: 'Buba Corelli', title: 'Nju bi da ljubim', year: 2017 },
  { artist: 'Cobi', title: 'Džepovi puni keša', year: 2018 },
  { artist: 'Cobi', title: 'Rambo', year: 2018 },
  { artist: 'Relja', title: 'Mi amore', year: 2019 },
  { artist: 'Relja', title: 'Dolce Vita', year: 2018 },
  { artist: 'Relja', title: 'Tuga iz Porschea', year: 2021 },
  { artist: 'Senidah', title: 'Crno srce', year: 2019 },
  { artist: 'Senidah', title: 'Belo', year: 2018 },
  { artist: 'Sanja Vučić', title: 'Hanuma', year: 2023 },
  { artist: 'Barbara Bobak', title: 'Slabić', year: 2024 },
  { artist: 'Barbara Bobak', title: 'Pogrešni', year: 2024 },
  { artist: 'Zera', title: 'Olako', year: 2022 },
  { artist: 'Mimi Mercedez', title: 'Kume', year: 2016 },
  { artist: 'Mimi Mercedez', title: 'Tik Tak', year: 2022 },
  { artist: 'Grše', title: 'Highlife', year: 2021 },
  { artist: 'Grše', title: 'Badr Hari', year: 2022 },
  { artist: 'Grše', title: 'Forza', year: 2024 },
  { artist: 'Zoi', title: 'Jasno mi je', year: 2019 },
  { artist: 'Zoi', title: 'Bez tebe', year: 2020 },
  { artist: 'Džordži', title: 'Loš sam ti ja', year: 2023 },
  { artist: 'Keni Nije Mrtav', title: 'Samuraj', year: 2022 },
  { artist: 'Buč Kesidi', title: 'Subota', year: 2020 },
  { artist: 'Buč Kesidi', title: 'Skupi snagu', year: 2023 }
];

// 4. Expanded Pop & Dance 90s/2000s & Regional Hits
const POPDANCE_ITEMS = [
  { artist: 'Colonia', title: 'Za tvoje snene oči', year: 2001 },
  { artist: 'Colonia', title: 'Oduzimaš mi dah', year: 2002 },
  { artist: 'Colonia', title: 'Svijet voli pobjednike', year: 2001 },
  { artist: 'Colonia', title: 'Plamen od ljubavi', year: 2003 },
  { artist: 'Colonia', title: 'Crying Time', year: 2003 },
  { artist: 'Colonia', title: 'Ti da bu di bu da', year: 2000 },
  { artist: 'Colonia', title: 'Njeno ime ne zovi u snu', year: 1999 },
  { artist: 'Karma', title: 'Sedam dana', year: 2003 },
  { artist: 'Karma', title: 'Amore mio', year: 2004 },
  { artist: 'Karma', title: 'Zemljotres', year: 2004 },
  { artist: 'Karma', title: 'Malo pomalo', year: 2005 },
  { artist: 'ET (Electro Team)', title: 'Tek je 12 sati', year: 1993 },
  { artist: 'ET (Electro Team)', title: 'Ne traži ljubav', year: 1994 },
  { artist: 'ET (Electro Team)', title: 'Da ti nisam bila dovoljna', year: 1996 },
  { artist: 'Dr Iggy', title: 'Oči boje duge', year: 1995 },
  { artist: 'Dr Iggy', title: 'Nikad', year: 1996 },
  { artist: 'Dr Iggy', title: 'Zašto ja', year: 1995 },
  { artist: 'Dr Iggy', title: 'Kada reči nisu potrebne', year: 1997 },
  { artist: 'Ivan Gavrilović', title: '200 na sat', year: 1994 },
  { artist: 'Ivan Gavrilović', title: 'Pevaj', year: 1995 },
  { artist: 'Ivan Gavrilović', title: 'Došao sam da te vidim', year: 1996 },
  { artist: 'Tap 011', title: 'Zbog tebe (Gaće)', year: 1995 },
  { artist: 'Tap 011', title: 'Vrapci', year: 1995 },
  { artist: 'Tap 011', title: 'Dosada', year: 1998 },
  { artist: 'Tap 011', title: 'Jeti', year: 1997 },
  { artist: 'Tap 011', title: 'Reka', year: 1998 },
  { artist: 'Đogani', title: 'Idemo na Mars', year: 1994 },
  { artist: 'Đogani', title: 'Balerina', year: 2003 },
  { artist: 'Đogani', title: 'Čekaj me kod kolima', year: 2004 },
  { artist: 'Đogani', title: 'Kao kao', year: 2005 },
  { artist: 'Đogani', title: 'Znam ja', year: 2007 },
  { artist: 'Funky G', title: 'Samo u snu', year: 1994 },
  { artist: 'Funky G', title: 'Budi tu', year: 1996 },
  { artist: 'Funky G', title: 'Dala bih sve', year: 2000 },
  { artist: 'Funky G', title: 'Gori more', year: 2001 },
  { artist: 'Funky G', title: 'Garavo', year: 2004 },
  { artist: 'Duck', title: 'Pedro', year: 1996 },
  { artist: 'Duck', title: 'Dačo, volim te', year: 1995 },
  { artist: 'Duck', title: 'Mala', year: 1997 },
  { artist: 'B3', title: 'Olovna ruka', year: 1996 },
  { artist: 'B3', title: 'Sperma', year: 1997 },
  { artist: 'B3', title: 'Ludo srce', year: 1998 },
  { artist: 'Beat Street', title: 'Snežana', year: 1995 },
  { artist: 'Beat Street', title: 'Ispovest', year: 1996 },
  { artist: 'Luna', title: '9 i po nedelja', year: 1998 },
  { artist: 'Luna', title: 'Naša ljubav', year: 2001 },
  { artist: 'Luna', title: 'Zeleno', year: 2002 },
  { artist: 'Luna', title: 'Plava košulja', year: 2000 },
  { artist: 'Energija', title: 'Suze', year: 1999 },
  { artist: 'Energija', title: 'Nedelja', year: 2000 },
  { artist: 'Energija', title: 'Snage mi ponestaje', year: 1999 },
  { artist: 'Moby Dick', title: 'Kralj kokaina', year: 1995 },
  { artist: 'Moby Dick', title: 'Zar nije te stid', year: 1994 },
  { artist: 'Moby Dick', title: 'Nostalgija', year: 1997 },
  { artist: 'Knez', title: 'Da l\' si ikada mene voljela', year: 1993 },
  { artist: 'Knez', title: 'Tina bambina', year: 1994 },
  { artist: 'Knez', title: 'Mia bella signorina', year: 1995 },
  { artist: 'Models', title: 'Pare, pare, pare', year: 1999 },
  { artist: 'Models', title: 'Šef stanice', year: 1999 },
  { artist: 'Ella B', title: 'Kamikaza', year: 1999 },
  { artist: 'Ella B', title: 'Ajkula', year: 1998 },
  { artist: 'Ella B', title: 'Oglas', year: 2001 },
  { artist: 'Denis & Denis', title: 'Program tvog kompjutera', year: 1984 },
  { artist: 'Denis & Denis', title: 'Soba 23', year: 1985 },
  { artist: 'Denis & Denis', title: 'Ja sam lažljiva', year: 1985 },
  { artist: 'Kasandra', title: 'Sladoled', year: 1995 },
  { artist: 'Kasandra', title: 'I Got A Feeling', year: 1995 },
  { artist: 'Ilan Kabiljo', title: 'Kad nema ljubavi', year: 1996 },
  { artist: 'Sandi Cenov', title: 'Malena', year: 1994 },
  { artist: 'Sandi Cenov', title: 'Ljubav za sve', year: 1995 },
  { artist: 'Nataša Bekvalac', title: 'Ponovo', year: 2005 },
  { artist: 'Nataša Bekvalac', title: 'Mali signali', year: 2002 },
  { artist: 'Nataša Bekvalac', title: 'Nikotin', year: 2005 },
  { artist: 'Nataša Bekvalac', title: 'Original', year: 2015 },
  { artist: 'Nataša Bekvalac', title: 'Dođi mami', year: 2019 },
  { artist: 'Emina Jahović', title: 'Da l\' ona zna', year: 2006 },
  { artist: 'Emina Jahović', title: 'Iza nas', year: 2008 },
  { artist: 'Emina Jahović', title: 'Med', year: 2009 },
  { artist: 'Jelena Karleuša', title: 'Slatka mala', year: 2005 },
  { artist: 'Jelena Karleuša', title: 'Upravo ostavljena', year: 2005 },
  { artist: 'Jelena Karleuša', title: 'Insomnia', year: 2010 },
  { artist: 'Jelena Karleuša', title: 'Muškarac koji mrzi žene', year: 2011 },
  { artist: 'Jelena Karleuša', title: 'Krimi rad', year: 2012 },
  { artist: 'Jelena Karleuša', title: 'Karleushex', year: 2023 },
  { artist: 'Ana Nikolić', title: 'Januar', year: 2003 },
  { artist: 'Ana Nikolić', title: 'Romale, romali', year: 2006 },
  { artist: 'Ana Nikolić', title: 'Mišo moj', year: 2010 },
  { artist: 'Ana Nikolić', title: 'Džukelo', year: 2010 },
  { artist: 'Ana Nikolić', title: 'Bilo je lepo', year: 2020 },
  { artist: 'Maya Berović', title: 'To me radi', year: 2016 },
  { artist: 'Maya Berović', title: 'Harem', year: 2017 },
  { artist: 'Maya Berović', title: 'Pravo vreme', year: 2018 },
  { artist: 'Maya Berović', title: 'Neka stvar', year: 2018 },
  { artist: 'Severina', title: 'Gas, gas', year: 2008 },
  { artist: 'Severina', title: 'Italiana', year: 2012 },
  { artist: 'Severina', title: 'Uzbuna', year: 2012 },
  { artist: 'Severina', title: 'Tarapana', year: 2012 },
  { artist: 'Severina', title: 'Moja štikla', year: 2006 },
  { artist: 'Severina', title: 'Djevojka sa sela', year: 1998 },
  { artist: 'Severina', title: 'Brad Pitt', year: 2011 },
  { artist: 'Jelena Rozga', title: 'Bižuterija', year: 2010 },
  { artist: 'Jelena Rozga', title: 'Nirvana', year: 2013 },
  { artist: 'Jelena Rozga', title: 'Okus mentola', year: 2014 },
  { artist: 'Jelena Rozga', title: 'Tsunami', year: 2014 },
  { artist: 'Lexington Band', title: 'Dobro da nije veće zlo', year: 2012 },
  { artist: 'Lexington Band', title: 'Potraži me', year: 2014 },
  { artist: 'Lexington Band', title: 'Donesi', year: 2014 },
  { artist: 'Tropico Band', title: 'Misliću na tebe', year: 2011 },
  { artist: 'Tropico Band', title: 'Zauvek tvoj', year: 2011 },
  { artist: 'Tropico Band', title: 'Sve moje zore', year: 2015 },
  { artist: 'Amadeus Band', title: 'Lažu te', year: 2005 },
  { artist: 'Amadeus Band', title: 'Moja zemlja', year: 2013 },
  { artist: 'Amadeus Band', title: 'Nije svejedno', year: 2009 },
  { artist: 'Dženan Lončarević', title: 'Nikome ni reč', year: 2007 },
  { artist: 'Dženan Lončarević', title: 'Laufer', year: 2015 },
  { artist: 'Dženan Lončarević', title: 'Cvete beli', year: 2013 },
  { artist: 'Adil', title: 'Laku noć', year: 2012 },
  { artist: 'Adil', title: 'Moje si nebo', year: 2017 },
  { artist: 'Adil', title: 'Maskenbal', year: 2013 },
  { artist: 'Peđa Medenica', title: 'Dođeš mi u san', year: 2014 },
  { artist: 'Peđa Medenica', title: 'Čisto da znaš', year: 2015 },
  { artist: 'Peđa Medenica', title: 'Imam ljubav', year: 2013 },
  { artist: 'Željko Samardžić', title: 'Grlica', year: 1995 },
  { artist: 'Željko Samardžić', title: 'Sipajte mi još jedan viski', year: 1995 },
  { artist: 'Željko Samardžić', title: 'Bezobrazno zelene', year: 2001 },
  { artist: 'Željko Samardžić', title: 'Da me nije', year: 1997 },
  { artist: 'Željko Samardžić', title: 'Stari lav', year: 2001 },
  { artist: 'Goca Tržan', title: 'Stoperka', year: 1999 },
  { artist: 'Goca Tržan', title: 'Zagrli me ti', year: 2001 },
  { artist: 'Goca Tržan', title: 'Haljina', year: 2004 },
  { artist: 'Jelena Tomašević', title: 'Oro', year: 2008 },
  { artist: 'Jelena Tomašević', title: 'Jutro', year: 2005 },
  { artist: 'Jelena Tomašević', title: 'Ime moje', year: 2015 },
  { artist: 'Ivana Selakov', title: 'Daleko si', year: 2012 },
  { artist: 'Ivana Selakov', title: 'Agonija', year: 2011 },
  { artist: 'Flamingosi', title: 'Ludi letnji ples', year: 2006 },
  { artist: 'Flamingosi', title: 'Obala', year: 2005 },
  { artist: 'Tijana Dapčević', title: 'Negativ', year: 2002 },
  { artist: 'Tijana Dapčević', title: 'Zemlja mojih snova', year: 2004 },
  { artist: 'Jelena Karleuša', title: 'Ludača', year: 2001 },
  { artist: 'Jelena Karleuša', title: 'Ko ovu dramu režira', year: 1998 },
  { artist: 'Jelena Karleuša', title: 'Gili gili', year: 1999 },
  { artist: 'Jelena Karleuša', title: 'Magija', year: 2005 },
  { artist: 'Jelena Karleuša', title: 'Ide maca oko tebe', year: 2005 },
  { artist: 'Jelena Karleuša', title: 'Casino', year: 2008 },
  { artist: 'Ana Nikolić', title: 'Devojka od čokolade', year: 2006 },
  { artist: 'Ana Nikolić', title: 'Plakaćete za mnom oboje', year: 2006 },
  { artist: 'Ana Nikolić', title: 'Ekstaza', year: 2010 },
  { artist: 'Ana Nikolić', title: 'Labilna', year: 2016 },
  { artist: 'Ana Nikolić', title: '200 sa 100', year: 2016 },
  { artist: 'Nataša Bekvalac', title: 'Ne brini', year: 2001 },
  { artist: 'Nataša Bekvalac', title: 'Bolja sam od nje', year: 2002 },
  { artist: 'Nataša Bekvalac', title: 'Gubim tlo pod nogama', year: 2004 },
  { artist: 'Nataša Bekvalac', title: 'Poludim li u 25', year: 2005 },
  { artist: 'Nataša Bekvalac', title: 'Pozitivna', year: 2012 },
  { artist: 'Emina Jahović', title: 'Uzalud se budim', year: 2002 },
  { artist: 'Emina Jahović', title: 'Tačka', year: 2003 },
  { artist: 'Emina Jahović', title: 'Limunada', year: 2017 },
  { artist: 'Severina', title: 'Krivi spoj', year: 2002 },
  { artist: 'Severina', title: 'Mili moj', year: 2002 },
  { artist: 'Severina', title: 'Prijateljice', year: 1998 },
  { artist: 'Severina', title: 'Virujen u te', year: 2001 },
  { artist: 'Severina', title: 'Pogled ispod obrva', year: 2001 },
  { artist: 'Jelena Rozga', title: 'Daj šta daš', year: 2008 },
  { artist: 'Jelena Rozga', title: 'Rodit ću ti kćer i sina', year: 2009 },
  { artist: 'Jelena Rozga', title: 'Cirkus', year: 2013 },
  { artist: 'Jelena Rozga', title: 'Kraljica', year: 2015 },
  { artist: 'Colonia', title: 'Budi mi zbogom', year: 1999 },
  { artist: 'Colonia', title: 'Mirno more', year: 2005 },
  { artist: 'Colonia', title: 'Deja vu', year: 2001 },
  { artist: 'Colonia', title: 'Luda glava balkanska', year: 2004 },
  { artist: 'Danijela Martinović', title: 'Neka mi ne svane', year: 1998 },
  { artist: 'Danijela Martinović', title: 'Da je slađe zaspati', year: 1998 },
  { artist: 'Danijela Martinović', title: 'Zovem te ja', year: 2001 },
  { artist: 'Doris Dragović', title: 'Marija Magdalena', year: 1999 },
  { artist: 'Doris Dragović', title: 'Željo moja', year: 1986 },
  { artist: 'Doris Dragović', title: 'Malo mi za sriću triba', year: 2002 },
  { artist: 'Maja Šuput', title: 'Lopove', year: 2015 },
  { artist: 'Maja Šuput', title: 'Kamikaza', year: 2017 },
  { artist: 'Maja Šuput', title: 'Amnezija', year: 2014 },
  { artist: 'Vesna Pisarović', title: 'Sasvim sigurna', year: 2002 },
  { artist: 'Vesna Pisarović', title: 'Da znaš', year: 2000 },
  { artist: 'Vesna Pisarović', title: 'Jutro donosi kraj', year: 2001 },
  { artist: 'Lana Jurčević', title: 'Prava ljubav', year: 2006 },
  { artist: 'Lana Jurčević', title: 'Majica', year: 2014 },
  { artist: 'Danijel Popović', title: 'Džuli', year: 1983 },
  { artist: 'Alka Vuica', title: 'Laži me', year: 1994 },
  { artist: 'Vanna', title: 'Kao da me nema tu', year: 2000 },
  { artist: 'Vanna', title: 'Daj mi jedan dobar razlog', year: 2001 },
  { artist: 'Magazin & Jelena Rozga', title: 'Suze biserne', year: 1996 },
  { artist: 'Magazin & Jelena Rozga', title: 'Opusti se', year: 1997 },
  { artist: 'Magazin & Jelena Rozga', title: 'Dani su bez broja', year: 2002 },
  { artist: 'Magazin & Danijela', title: 'Svileni', year: 1994 },
  { artist: 'Magazin & Danijela', title: 'Došlo vrijeme', year: 1993 },
  { artist: 'Magazin & Ljiljana Nikolovska', title: 'Piši mi', year: 1985 },
  { artist: 'Magazin & Ljiljana Nikolovska', title: 'Put putujem', year: 1986 },
  { artist: 'Magazin & Ljiljana Nikolovska', title: 'Tri sam ti zime šaptala ime', year: 1987 },
  { artist: 'Magazin & Ljiljana Nikolovska', title: 'Rano, ranije', year: 1989 }
];

function generateFile(category, prefix, items, outPath) {
  const songs = items.map((item, i) => {
    const searchTerms = makeSearchTerms(item.title, item.artist);
    return {
      id: `${prefix}-exp-${i + 1}`,
      title: item.title,
      artist: item.artist,
      year: item.year,
      genre: category,
      searchTerms: searchTerms,
      previewQuery: `${item.artist} ${item.title}`
    };
  });

  const content = `import { Song } from '../../types';\n\nexport const EXPANDED_${prefix.toUpperCase()}_SONGS: Song[] = ${JSON.stringify(songs, null, 2)};\n`;
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`Generated ${songs.length} songs for ${prefix} at ${outPath}`);
}

generateFile('narodna', 'narodna', NARODNA_ITEMS, path.resolve(process.cwd(), 'src/data/songs/expandedNarodna.ts'));
generateFile('ex-yu', 'exyu', EXYU_ITEMS, path.resolve(process.cwd(), 'src/data/songs/expandedExYu.ts'));
generateFile('moderno', 'moderno', MODERNO_ITEMS, path.resolve(process.cwd(), 'src/data/songs/expandedModerno.ts'));
generateFile('pop-dance', 'popdance', POPDANCE_ITEMS, path.resolve(process.cwd(), 'src/data/songs/expandedPopDance.ts'));
